layout_spectrum: 0.0811925
color:
  saturation: 0.1564174
  lightness: 0.1179787
  brandStrength: 0.6201724
  rhythmicContrast: 0.5660005
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.6756272
name: Vadim Zendejas
