name: Vadim Zendejas
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8f8'
    - '#b8b8b8'
    - '#3585b6'
    - '#5fccf7'
    - '#7a7a7a'
  brandStrength: 0.6201724
  lightness: 0.1179787
  saturation: 0.1564174
  rhythmicContrast: 0.5660005
purpose: []
